axis_test:
  ros__parameters:
    planning_group: ur_manipulator
    
    test_speed: 0.03

    center_x: 1.0
    center_y: 0.0
    center_z: 0.35

    y_travel: 0.4
    z_travel: 0.25

    rotation_rad: 1.57
    eef_step: 0.01
    park_joints: [-0.2044, -0.7735, 2.0590, -2.8312, -1.5607, 0.8894]
