jog_to_rest:
  ros__parameters:
    planning_group: ur_manipulator
    # Fraction (0-1] of maximum joint velocity/acceleration.
    velocity_scaling: 0.05
    acceleration_scaling: 0.1

    # How far the camera tip sticks out of the flange along tool z (m).
    camera_length: 0.22

    # EOD rest pose
    rest_joints: [-0.1504, -1.7453, 2.5307, -2.3562, -1.5586, 0.9208]
