tcp_orientate:
  ros__parameters:
    planning_group: ur_manipulator

    test_speed: 0.03
    wiggle_rad: 0.2
    
    # The test first moves here 
    park_joints: [-0.2044, -0.7735, 2.0590, -2.8312, -1.5607, 0.8894]
